"""Asset catalog: identity, conservative relations, and bounded read-only scanning."""
import json
import sys
import tempfile
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from workbench.adapters import assets


class TestAssets(unittest.TestCase):
    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory()
        self.addCleanup(self.tmp.cleanup)
        self.root = Path(self.tmp.name) / "project"
        self.home = Path(self.tmp.name) / "home"
        self.root.mkdir()
        self.home.mkdir()

    def write(self, rel, value, home=False):
        p = (self.home if home else self.root) / rel
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(value, encoding="utf-8")
        return p

    def catalog(self):
        return assets.load_assets(self.root, home=self.home)

    def manifest(self, path="common/rule.md"):
        self.write("knowledge/aclnn/manifest.json", json.dumps({"family": "aclnn", "modules": [
            {"id": "rule", "path": path, "scope": "common", "default_load": True}]}))
        self.write("knowledge/aclnn/common/rule.md", "---\nmodule: rule\ndescription: 解释维度规则\n---\n# 维度规则\n")

    def agent(self, extra=""):
        self.write(".opencode/agent/constraint-extractor.md", "---\ndescription: 提取约束\n---\n"
                   "开工第一步：立即用 skill 工具加载 `extract-constraints` 技能。\n" + extra)
        self.write(".opencode/skills/extract-constraints/SKILL.md", "---\ndescription: 从文档提取约束\n---\n")

    def test_absent_user_dirs_keep_project_assets(self):
        self.agent()
        result = self.catalog()
        self.assertEqual(len(result["skills"]), 1)
        self.assertTrue(all(g["status"] == "missing" for g in result["user_groups"]))

    def test_manifest_wins_over_missing_generated_marker(self):
        self.manifest()
        self.write(".opencode/skills/aclnn-rule/SKILL.md", "---\ndescription: 生成技能\n---\n")
        result = self.catalog()
        self.assertEqual(result["skills"], [])
        self.assertEqual(result["knowledge"][0]["description"], "解释维度规则")

    def test_orphan_generated_skill_not_classified_as_handwritten(self):
        self.write(".opencode/skills/aclnn-old/SKILL.md", "---\ndescription: 旧知识\n---\n<!-- GENERATED by scripts/build_knowledge_skills.py -->")
        result = self.catalog()
        self.assertEqual(result["skills"], [])
        self.assertEqual(result["knowledge"][0]["availability"], "unavailable")

    def test_knowledge_permission_requires_current_text(self):
        self.agent("知识 skill（aclnn→`aclnn-*`，hs→`torch-npu-*`）允许且必须按必载协议加载。")
        result = self.catalog()
        self.assertEqual(result["agents"][1]["knowledge_access"], "conditional")
        self.agent()
        self.assertEqual(self.catalog()["agents"][1]["knowledge_access"], "unmentioned")

    def test_user_duplicates_keep_installations_but_one_capability(self):
        for directory in (".agents/skills", ".claude/skills"):
            self.write(directory + "/arkcli-test/SKILL.md", "---\nname: arkcli-test\ndescription: >\n  查询模型\n  和服务状态\n---\nSECRET BODY", home=True)
        result = self.catalog()
        self.assertEqual(len(result["extensions"]), 1)
        self.assertEqual(len(result["extensions"][0]["installations"]), 2)
        self.assertIn("查询模型", result["extensions"][0]["description"])
        self.assertNotIn("SECRET BODY", json.dumps(result))
        self.assertNotIn(str(self.home), json.dumps(result))

    def test_user_symlink_outside_whitelist_is_not_read(self):
        secret = self.write("secret/SKILL.md", "---\ndescription: MUST NOT LEAK\n---")
        directory = self.home / ".agents/skills/arkcli-escape"
        directory.parent.mkdir(parents=True)
        directory.symlink_to(secret.parent, target_is_directory=True)
        result = self.catalog()
        self.assertNotIn("MUST NOT LEAK", json.dumps(result))
        self.assertEqual(result["user_groups"][1]["status"], "partial")

    def test_project_symlink_and_manifest_escape_are_rejected(self):
        secret = self.write("private.md", "---\ndescription: DO NOT EXPOSE\n---")
        directory = self.root / ".opencode/skills/escape"
        directory.mkdir(parents=True)
        (directory / "SKILL.md").symlink_to(secret)
        self.manifest("../../private.md")
        result = self.catalog()
        self.assertNotIn("DO NOT EXPOSE", json.dumps(result))
        self.assertTrue(result["warnings"])

    def test_malformed_description_is_not_an_empty_success(self):
        self.write(".opencode/skills/broken/SKILL.md", "---\ndescription: unfinished")
        result = self.catalog()
        self.assertEqual(result["skills"][0]["availability"], "unavailable")
        self.assertTrue(result["warnings"])


if __name__ == "__main__":
    unittest.main()
