"""Read-only asset catalog. Definitions describe capability, not runtime use.

Keep user files bounded and metadata-only. Manifest identity takes precedence
over generated comments. Unknown relationships are never permission denials.
"""
import fnmatch
import json
import re
from pathlib import Path

from .. import paths
from ..parsers.frontmatter import parse_frontmatter
from .agents import _body_of, _skills_from_body, _skills_from_meta
from .stage_inference import AGENTS_FLOW

MAX_READ = 512 * 1024
MAX_META = 32 * 1024
NAME = re.compile(r"^[A-Za-z0-9_-]+$")
GENERATED = "GENERATED by scripts/build_knowledge_skills.py"


def _read(path):
    with path.open("rb") as stream:
        data = stream.read(MAX_READ + 1)
    if len(data) > MAX_READ:
        raise ValueError("文件过大")
    return data.decode("utf-8")


def _metadata(text):
    """Only scalar name/description from bounded YAML frontmatter, no YAML execution.

    Supports folded/literal descriptions; skips complex trigger/permission data.
    """
    lines = text.splitlines()
    if not lines or lines[0].strip() != "---":
        raise ValueError("缺少技能说明")
    end = next((i for i in range(1, len(lines)) if lines[i].strip() == "---"), None)
    if end is None:
        raise ValueError("说明未闭合")
    result = {}
    for i in range(1, end):
        match = re.match(r"^(name|description):\s*(.*)$", lines[i])
        if not match:
            continue
        key, value = match.groups()
        if value in (">", ">-", ">+", "|", "|-", "|+"):
            parts = []
            for line in lines[i + 1:end]:
                if line and not line[0].isspace():
                    break
                parts.append(line.strip())
            value = " ".join(parts)
        elif len(value) >= 2 and value[0] == value[-1] == "'":
            value = value[1:-1].replace("''", "'")
        elif len(value) >= 2 and value[0] == value[-1] == '"':
            try:
                value = json.loads(value)
            except ValueError:
                value = value[1:-1]
        result[key] = value
    if not result.get("description"):
        raise ValueError("缺少用途说明")
    return result


def _user_metadata(path):
    # Stop at the closing delimiter; never collect or return the skill body.
    lines, size = [], 0
    with path.open("rb") as stream:
        while size <= MAX_META:
            line = stream.readline(MAX_META + 1)
            if not line:
                break
            size += len(line)
            if size > MAX_META:
                raise ValueError("说明过长")
            lines.append(line.decode("utf-8"))
            if len(lines) > 1 and line.strip() == b"---":
                return _metadata("".join(lines))
    raise ValueError("无法读取技能说明")


def _files(base, pattern):
    # Do not even enumerate a collection whose root redirects outside the boundary.
    if base.resolve() != base.absolute():
        raise paths.PathEscapeError("资产目录指向其他位置")
    return sorted(base.glob(pattern))


def _knowledge_access(name, text):
    # Deliberately narrow, verified declarations, not a guess based on role names.
    clauses = {
        "constraint-extractor": ("允许且必须按必载协议", "conditional"),
        "constraint-checker": ("允许通过 skill 工具加载", "conditional"),
        "constraint-repairer": ("知识 skill 按需加载", "conditional"),
        "constraint-supplementer": ("知识 skill 按需加载", "conditional"),
        "constraint-updater": ("知识 skill 按需加载", "conditional"),
        "failure-analyst": ("知识 skill 按需加载", "conditional"),
        "prompt-optimizer": ("knowledge/aclnn/", "reference"),
    }
    clause, access = clauses.get(name, (None, "unmentioned"))
    return access if clause and clause in text else "unmentioned"


def _agents(root, warnings):
    base = root / ".opencode/agent"
    if not base.exists():
        base = root / ".claude/agents"
    found = {}
    try:
        files = _files(base, "*.md")
    except (OSError, ValueError):
        files = []
        warnings.append("部分智能体信息暂不可用")
    for file in files:
        entry = {"name": file.stem, "description": "", "skills": [], "color": "blue",
                 "knowledge_access": "unmentioned", "skill_policy": {}, "availability": "ready"}
        try:
            text = _read(paths.resolve_asset(base, file.name))
            meta = parse_frontmatter(text)
            if meta.get("_error"):
                raise ValueError("定义无法解析")
            entry.update(description=_metadata(text)["description"], color=meta.get("color", "blue"))
            entry["skills"] = _skills_from_meta(meta) or _skills_from_body(_body_of(text))
            permission = meta.get("permission", {})
            if isinstance(permission, dict):
                entry["skill_policy"] = permission.get("skill", {})
            combined = text
            for skill in entry["skills"]:
                if NAME.fullmatch(skill):
                    try:
                        combined += "\n" + _read(paths.resolve_asset(root / ".opencode/skills", skill + "/SKILL.md"))
                    except (OSError, ValueError):
                        pass
            entry["knowledge_access"] = _knowledge_access(file.stem, combined)
        except (OSError, ValueError):
            entry["availability"] = "unavailable"
            warnings.append("部分智能体说明暂不可用")
        found[file.stem] = entry
    ordered = []
    for spec in AGENTS_FLOW:
        entry = found.pop(spec["name"], {"name": spec["name"], "description": "", "skills": [],
                    "knowledge_access": "unmentioned", "skill_policy": {}, "color": "gray", "availability": "missing"})
        ordered.append({**entry, "role": spec["role"], "stage": spec["stage"], "optional": spec["optional"]})
    ordered.extend({**e, "role": e["name"], "stage": None, "optional": True} for e in found.values())
    return ordered


def _denied(policy, name):
    if isinstance(policy, str):
        return policy == "deny"
    decision = None
    if isinstance(policy, dict):
        for pattern, value in policy.items():
            if fnmatch.fnmatchcase(name, pattern):
                decision = value
    return decision == "deny"


def load_assets(root, home=None):
    root = Path(root).resolve()
    home = Path.home() if home is None else Path(home)
    warnings, knowledge, skills, expected = [], [], [], set()
    agents = _agents(root, warnings)
    for family, prefix in (("aclnn", "aclnn-"), ("torch_npu", "torch-npu-")):
        base = root / "knowledge" / family
        try:
            manifest = json.loads(_read(paths.resolve_asset(base, "manifest.json")))
            modules = manifest["modules"]
            if not isinstance(modules, list):
                raise ValueError("模块清单无效")
        except (OSError, ValueError, KeyError, TypeError):
            warnings.append(f"{family} 知识信息暂不可用")
            continue
        for module in modules:
            if not isinstance(module, dict) or not isinstance(module.get("id"), str) or not NAME.fullmatch(module["id"]):
                warnings.append("部分知识信息暂不可用")
                continue
            name = prefix + module["id"].replace("_", "-")
            expected.add(name)
            entry = {"id": "knowledge:" + family + ":" + module["id"], "name": name,
                     "module": module["id"], "family": family, "scope": module.get("scope", "other"),
                     "description": "", "kind": "knowledge", "availability": "ready"}
            try:
                relative = module.get("path")
                if not isinstance(relative, str) or not relative.endswith(".md"):
                    raise ValueError("知识位置无效")
                entry["description"] = _metadata(_read(paths.resolve_asset(base, relative)))["description"]
                paths.resolve_asset(root / ".opencode/skills", name + "/SKILL.md")
            except (OSError, ValueError):
                entry["availability"] = "unavailable"
                warnings.append("部分知识说明或能力暂不可用")
            knowledge.append(entry)
    base = root / ".opencode/skills"
    try:
        files = _files(base, "*/SKILL.md")
    except (OSError, ValueError):
        files = []
        warnings.append("项目技能暂不可用")
    for file in files:
        name = file.parent.name
        if name in expected:
            continue
        entry = {"id": "skill:" + name, "name": name, "kind": "skill", "description": "", "availability": "ready"}
        try:
            text = _read(paths.resolve_asset(base, name + "/SKILL.md"))
            if GENERATED in text or name.startswith(("aclnn-", "torch-npu-")):
                knowledge.append({**entry, "kind": "knowledge", "family": "aclnn" if name.startswith("aclnn-") else "torch_npu",
                                  "module": name, "scope": "other", "availability": "unavailable"})
                warnings.append("部分知识能力需要检查")
                continue
            entry["description"] = _metadata(text)["description"]
        except (OSError, ValueError):
            entry["availability"] = "unavailable"
            warnings.append("部分技能说明暂不可用")
        skills.append(entry)
    extensions, user_groups = {}, []
    for directory, label in zip(paths.USER_SKILL_DIRS, ("OpenCode", "通用智能体", "Claude")):
        base = home.resolve() / directory
        group = {"label": label, "status": "ready", "count": 0}
        user_groups.append(group)
        if not base.exists() and not base.is_symlink():
            group["status"] = "missing"
            continue
        try:
            files = _files(base, "*/SKILL.md")
            if not files:
                group["status"] = "empty"
            for file in files:
                name = file.parent.name
                if not (name.startswith(("arkcli-", "byted-")) or name == "find-skills"):
                    continue
                try:
                    meta = _user_metadata(paths.resolve_user_skill(home, directory, name))
                    identity = meta.get("name") or name
                    item = extensions.setdefault(identity, {"id": "user:" + identity, "name": identity,
                          "description": meta["description"], "kind": "extension", "availability": "ready", "installations": []})
                    item["installations"].append({"label": label, "description": meta["description"]})
                    group["count"] += 1
                except (OSError, ValueError):
                    group["status"] = "partial"
            if not group["count"] and group["status"] == "ready":
                group["status"] = "empty"
        except (OSError, ValueError):
            group["status"] = "unavailable"
    for agent in agents:
        policy = agent.pop("skill_policy")
        agent["relations"] = {}
        for item in skills + knowledge:
            access = "unmentioned"
            if agent["availability"] == "ready":
                if item["name"] in agent["skills"]:
                    access = "required"
                elif item["kind"] == "knowledge":
                    access = agent["knowledge_access"]
                if _denied(policy, item["name"]):
                    access = "denied"
            agent["relations"][item["id"]] = access
    return {"agents": agents, "skills": skills, "knowledge": knowledge,
            "extensions": list(extensions.values()), "user_groups": user_groups,
            "warnings": sorted(set(warnings))}
