# Copyright (c) Huawei Technologies Co., Ltd. 2023. All rights reserved.
# Auto-generated by generator.py
# Fixed template for aclnnGroupedMatmulV5 — edit this file directly when the
# NPU-side executor logic needs adjustment.  The CPU golden section is MOCKED
# since 2026-09-21 (shape-aware zeros, same contract as the generic template);
# the real derived golden lives in git history.

import copy
import ctypes
import re

import torch
from atk.common.log import Logger
from atk.configs.dataset_config import InputDataset
from atk.configs.results_config import TaskResult
from atk.tasks.api_execute import register
from atk.tasks.api_execute.aclnn_base_api import AclnnBaseApi
from atk.tasks.api_execute.base_api import BaseApi
from atk.tasks.backends.lib_interface.acl_wrapper import Int64, Uint64, AclTensorStruct, TORCH_TO_ACLTYPE, nnopbase, AclFormat, aclnn, AclnnStatus, TensorPtr ,AclTensorlistStruct, pointer, AclIntArray, AclTensor, AclTensorList, AclDataType

logging = Logger().get_logger()


# ============================================================================
# GroupedMatmulV5 helper functions (module-level, shared by NPU and CPU paths)
# ============================================================================

def _build_grouped_matmul_v5_group_list(
        m, group_count, group_list_type, device=None):
    """Build deterministic type-0/1/2 group-list content covering M."""
    m = int(m)
    group_count = int(group_count)
    group_list_type = int(group_list_type)
    if m < 0:
        raise ValueError("GroupedMatmulV5 M must be non-negative")
    if group_count <= 0:
        raise ValueError("GroupedMatmulV5 group count must be positive")
    if group_list_type not in (0, 1, 2):
        raise ValueError(
            f"Unsupported GroupedMatmulV5 groupListType: {group_list_type}"
        )

    base, remainder = divmod(m, group_count)
    group_sizes = torch.full(
        (group_count,), base, dtype=torch.int64, device=device
    )
    if remainder:
        group_sizes[:remainder] += 1
    if group_list_type == 0:
        return torch.cumsum(group_sizes, dim=0)
    if group_list_type == 1:
        return group_sizes
    group_indexes = torch.arange(
        group_count, dtype=torch.int64, device=device
    )
    return torch.stack((group_indexes, group_sizes), dim=1)


def _build_grouped_matmul_v5_group_list_from_sizes(
        sizes, group_list_type, device):
    """Deterministic groupList content from explicit per-group row counts.

    多-x（多多单）专用：组 i 的行数 = x_i 的第一维（位置配对语义），
    不做均匀拆分近似。type0=cumsum(sizes) / type1=sizes / type2=(idx,size)。
    """
    sizes_tensor = torch.tensor(sizes, dtype=torch.int64, device=device)
    if group_list_type == 0:
        return torch.cumsum(sizes_tensor, dim=0)
    if group_list_type == 1:
        return sizes_tensor
    group_indexes = torch.arange(
        len(sizes), dtype=torch.int64, device=device
    )
    return torch.stack((group_indexes, sizes_tensor), dim=1)


def _prepare_grouped_matmul_v5_group_list(
        x_value, weight_value, group_list, group_type, group_list_type):
    """Materialise type-0/1/2 content for groupType=0 single-list cases.

    Covers quantized (int8/int32-logical-int4) and non-quantized
    (fp32/fp16/bf16) A2 documented scenarios alike: the materialisation
    only consumes x dim-0 (M) and the group count, so the documented
    dtypes share one content path. 多-x（多多单）同样支持：内容按 x_i
    逐组尺寸物化（位置配对），见 _build_grouped_matmul_v5_group_list_from_sizes。
    """
    def single_tensor(value):
        if isinstance(value, torch.Tensor):
            return value
        if (isinstance(value, (list, tuple)) and len(value) == 1
                and isinstance(value[0], torch.Tensor)):
            return value[0]
        return None

    x_tensor = single_tensor(x_value)
    weight_tensor = single_tensor(weight_value)
    # A8W4 伪量化多 Tensor：weight 为 TensorList（E 个 rank-2 量化权重）。
    # NPU 侧 handle_special_param 已折算 int8；CPU golden 侧为原始 int32
    # 逻辑值——两种 dtype 都要命中作用域，保证两侧物化一致。
    weight_list = None
    if weight_tensor is None and isinstance(weight_value, (list, tuple)):
        items = list(weight_value)
        if items and all(isinstance(w, torch.Tensor) for w in items):
            weight_list = items
    # 多-x（多多单，L627）：x 为 TensorList（多个 2D 张量），x_i 与
    # weight_i 位置配对，组 i 覆盖 x_i 全部行（k_i 可不同，L66/L69）。
    x_list = None
    if x_tensor is None and isinstance(x_value, (list, tuple)):
        x_items = list(x_value)
        if x_items and all(
            isinstance(t, torch.Tensor) and t.dim() == 2 for t in x_items
        ):
            x_list = x_items
    scope_dtypes = (
        torch.float32, torch.float16, torch.bfloat16,
        torch.int8, torch.int32,
    )
    in_supported_scope = (
        group_type == 0
        and group_list_type in (0, 1, 2)
        and (
            (x_tensor is not None and x_tensor.dim() == 2
             and x_tensor.dtype in scope_dtypes)
            or (x_list is not None
                and all(t.dtype in scope_dtypes for t in x_list))
        )
        and (
            (
                isinstance(weight_tensor, torch.Tensor)
                and weight_tensor.dim() == 3
                and weight_tensor.dtype in scope_dtypes
            )
            or (
                weight_list is not None
                and all(
                    w.dim() == 2 and w.dtype in scope_dtypes
                    for w in weight_list
                )
            )
        )
    )
    if not in_supported_scope:
        if group_type == 0 and group_list is not None:
            # gt=0 带 groupList 但落在物化 scope 外：ATK 按 range 随机生成
            # groupList 内容，直通内核会按错误行偏移读 x——20260920 run
            # iter_001 FC-001 实证 groupList=[1024 个 2147483647]（fp32
            # 非量化曾被 dtype 限定排除在 scope 外）内核挂起约 10 分钟后
            # aicore timeout 并毒化设备级联。fail-closed 显式报错，
            # 禁止静默透传随机内容。
            raise ValueError(
                "GroupedMatmulV5 groupType=0 groupListOptional content "
                "materialisation scope unsupported (x/weight dtype or "
                "rank out of documented scope); refusing to pass random "
                "groupList content to the kernel"
            )
        # groupList 缺省（多多单 L627 可选）与 gt=-1/2 场景维持原行为。
        return group_list
    if not isinstance(group_list, torch.Tensor):
        if weight_list is not None:
            # 多多单（L627）groupList 可选：缺省透传 nullptr 属文档合法
            # 形态；dtype 扩展后非量化 fp32 多多单缺省用例落入 scope，
            # 不得误触单 weight 分支的必传校验。
            return None
        raise ValueError(
            "GroupedMatmulV5 groupListOptional is required in the "
            "groupType=0 single-list scope"
        )
    if group_list.dtype != torch.int64:
        raise ValueError(
            "GroupedMatmulV5 groupListOptional dtype must be torch.int64"
        )

    # 用例生成器不填充 groupList 值语义（ATK 按 range 随机生成）；多 Tensor
    # 场景随机值 sum != M 会令内核按错误行偏移读 x，触发 MTE invalid GM
    # address（EZ9999 aicore exception）并毒化设备级联。与单 3-D 分支同理
    # 按确定内容物化（type0=cumsum 偏移 / type1=分组行数 / type2=(idx,size)），
    # NPU 与 CPU golden 共用本函数保证两侧取值一致。
    if weight_list is not None:
        group_count = len(weight_list)
    else:
        group_count = int(weight_tensor.shape[0])
    expected_shape = (
        (group_count, 2) if group_list_type == 2 else (group_count,)
    )
    if tuple(group_list.shape) != expected_shape:
        raise ValueError(
            "GroupedMatmulV5 groupListOptional shape must be "
            f"{expected_shape} for groupListType={group_list_type}, got "
            f"{tuple(group_list.shape)}"
        )
    if x_list is not None:
        # 多-x：内容按 x_i 逐组尺寸确定性物化（组 i = x_i 全部行），NPU
        # 与 CPU golden 共用；len(x) != len(weight) 的位置配对无定义，
        # fail-closed 拒绝（C-057 约束亦应拦截该组合）。
        if len(x_list) != group_count:
            raise ValueError(
                "GroupedMatmulV5 groupType=0 multi-x requires "
                "len(weight) == len(x) for positional pairing, got "
                f"{group_count} vs {len(x_list)}"
            )
        sizes = [int(t.shape[0]) for t in x_list]
        return _build_grouped_matmul_v5_group_list_from_sizes(
            sizes, group_list_type, group_list.device
        )
    return _build_grouped_matmul_v5_group_list(
        x_tensor.shape[0], group_count, group_list_type, group_list.device
    )


def _prepare_grouped_matmul_v5_weight(
        tensor, group_type, weight_transposed):
    """Materialise documented cases layout into the ACLNN tensor layout."""
    if not isinstance(tensor, torch.Tensor) or tensor.dim() < 2:
        return tensor

    # 3-D（groupType=0）：cases 层按文档 L595-597 约定 False 存 (E,K,N)、
    # True 存 (E,N,K)（末维 N/K 轴），ACLNN 消费数学 (E,K,N)；True 分支以
    # 非连续转置 view 的 stride 信号承载转置标志。按 md 权威约定去 dtype
    # 限定：int8 与浮点（fp32/fp16/bf16）共用本分支；int4（torch.int32
    # 逻辑值）走下方 A4W4 专属分支。原 int8 限定使 3-D 浮点 True 用例
    # fallthrough 原样透传 (E,N,K)，20260917 run iter_001 FC-002 同类缺陷。
    if (group_type == 0 and tensor.dim() == 3
            and tensor.dtype != torch.int32):
        if weight_transposed:
            # cases (E,N,K) -> mathematical (E,K,N), non-contiguous view.
            return tensor.transpose(-1, -2)
        # cases already store contiguous (E,K,N).
        return tensor.contiguous()

    # A4W4 全量化：cases 层 weight 逻辑 shape 恒为 (E,K,N)（weight_transposed
    # 是"先转置再 NZ"的 NPU 物化模式标识）。ATK 以 torch.int32 逻辑值生成
    # int4 数据；先按 weight_transposed 物化转置布局，再折算到 [-8,7] 的
    # int8，由 create_int4_acl_tensor 打包为 ACL_INT4（逻辑 shape 不变，
    # 不做 8x 末维展开）。
    if group_type == 0 and tensor.dim() == 3 and tensor.dtype == torch.int32:
        if weight_transposed:
            # 先转置再 NZ：宿主要求 ACL 视图 shape 恒为 (E,K,N)（dim1=K 与
            # x 对齐），转置语义由 strides 表达（IsTransposeLastTwoDims 判
            # 定 transposeWeight）。因此数据物化为物理 (E,N,K) 顺序，返回
            # 其转置视图（shape (E,K,N)、strides (N*K,1,K)）。
            phys = tensor.transpose(-1, -2).contiguous()
            return _int4_nibble_wrap(phys).transpose(-1, -2)
        return _int4_nibble_wrap(tensor.contiguous())

    # A8W4 伪量化 rank-2 weight（groupType=0 多 Tensor / groupType=-1）：
    # ATK 以 torch.int32 逻辑值生成 int4 数据。与上面 3-D INT4 分支同理，
    # cases 层 weight 逻辑 shape 恒为 (K,N)（CPU golden INT4 路径即按
    # 原样 matmul，weight_transposed 仅为 NPU"先转置再 NZ"物化标识，
    # 与 rank-2 浮点分支的 (N,K) 约定不同）。折算 [-8,7] int8 后由
    # _create_int4_acl_tensor 按视图 shape/strides 打包为 ACL_INT4。
    if (group_type in (-1, 0) and tensor.dim() == 2
            and tensor.dtype == torch.int32):
        if weight_transposed:
            # 先转置再 NZ：物化物理 (N,K) 顺序，返回转置视图
            # （shape (K,N)、strides (1,K)）。
            phys = tensor.transpose(-1, -2).contiguous()
            return _int4_nibble_wrap(phys).transpose(-1, -2)
        return _int4_nibble_wrap(tensor.contiguous())

    # groupType∈{-1,0}, rank-2: 按文档 L595-597 / md 权威约定，cases 层 weight
    # False 存 (K,N)（末维 N 轴）、True 存 (N,K)（末维 K 轴）；ACLNN 两个分支都
    # 消费数学 (K,N)（dim 0 == K == x dim 1）：False 保持连续 (K,N)，True 变为
    # (N,K) 存储上的非连续转置 view（stride 信号承载转置标志，由 NPU 物化）。
    # 浮点 (fp32/fp16/bf16) 与 int8（A16W8）共用同一约定。旧实现按 (N,K)-False
    # 约定写反两个分支（20260909 run iter_001 FC-004 证伪后 md 已更正，
    # 20260917 run iter_001 FC-002 实证本模板漏同步：非方阵 weight 全部
    # matmul 形状不匹配（CPU 侧）/ EZ1001（NPU 侧））。
    if (group_type in (-1, 0) and tensor.dim() == 2
            and tensor.dtype in (
                torch.float32, torch.float16, torch.bfloat16, torch.int8)):
        if weight_transposed:
            # cases (N,K) -> mathematical (K,N), non-contiguous transposed view.
            return tensor.transpose(-1, -2)
        # cases already store contiguous (K,N).
        return tensor.contiguous()

    return tensor


def _grouped_matmul_v5_weight_for_matmul(
        tensor, group_type, weight_transposed):
    """Restore a cases-layer weight to its mathematical matmul layout."""
    if not isinstance(tensor, torch.Tensor):
        return tensor

    if group_type == 2 and tensor.dim() == 2:
        return tensor

    if group_type in (-1, 0) and tensor.dim() == 2:
        # Documented 2-D cases convention (md 权威约定 / doc L595-597): False
        # stores (K,N) (last dim N); True stores (N,K) (last dim K) ->
        # transpose to mathematical (K,N). 旧实现两分支写反，20260917 run
        # iter_001 FC-002 实证后按 aclnn_api_template.py.j2 同步。
        return tensor.transpose(-1, -2) if weight_transposed else tensor

    if group_type == 0 and tensor.dim() == 3:
        return tensor.transpose(-1, -2) if weight_transposed else tensor

    raise ValueError(
        "Unsupported GroupedMatmulV5 CPU weight layout: "
        f"groupType={group_type}, rank={tensor.dim()}, "
        f"weight_transposed={weight_transposed}"
    )


def _grouped_matmul_v5_broadcast_perchannel(param, weight, name):
    """Validate and align A16W8 per-channel data to logical N."""
    if param is None:
        return None
    if not isinstance(param, torch.Tensor):
        raise TypeError(f"GroupedMatmulV5 {name} must be a tensor")

    value = param.float()
    if weight.dim() == 2:
        expected = (weight.shape[-1],)
        if tuple(value.shape) != expected:
            raise ValueError(
                f"GroupedMatmulV5 {name} must have shape [N]={expected}, "
                f"got {tuple(value.shape)}"
            )
        return value.unsqueeze(0)

    if weight.dim() == 3:
        expected = (weight.shape[0], weight.shape[-1])
        if tuple(value.shape) != expected:
            raise ValueError(
                f"GroupedMatmulV5 {name} must have shape [E,N]={expected}, "
                f"got {tuple(value.shape)}"
            )
        return value.unsqueeze(-2)

    raise ValueError(
        "GroupedMatmulV5 per-channel dequant requires rank-2 or rank-3 "
        f"weight, got rank {weight.dim()}"
    )


def _grouped_matmul_v5_dequant_perchannel(weight, scale, offset=None):
    """Apply A16W8 dequant as (weight + offset) * scale."""
    value = weight.float()
    offset_value = _grouped_matmul_v5_broadcast_perchannel(
        offset, value, "antiquantOffsetOptional"
    )
    scale_value = _grouped_matmul_v5_broadcast_perchannel(
        scale, value, "antiquantScaleOptional"
    )
    if scale_value is None:
        raise ValueError(
            "GroupedMatmulV5 A16W8 requires antiquantScaleOptional"
        )
    if offset_value is not None:
        value = value + offset_value
    return value * scale_value


def _int4_nibble_wrap(tensor):
    """Fold int values into signed INT4 range [-8, 7] as torch.int8.

    ATK materialises "int4" case data as torch.int32 logical values (one
    nibble value per element, logical shape), so no nibble unpack happens
    anywhere. Both NPU and CPU paths only need this value fold before the
    2-nibbles-per-byte packing done by create_int4_acl_tensor.
    """
    if not isinstance(tensor, torch.Tensor):
        return tensor
    value = torch.remainder(tensor.to(torch.int64), 16)
    value = torch.where(value >= 8, value - 16, value)
    return value.to(torch.int8)


def _int4_nibble_wrap_value(value):
    """List-aware _int4_nibble_wrap for runtime tensor-list values."""
    if isinstance(value, torch.Tensor):
        return _int4_nibble_wrap(value)
    if isinstance(value, list):
        return [_int4_nibble_wrap_value(item) for item in value]
    if isinstance(value, tuple):
        return tuple(_int4_nibble_wrap_value(item) for item in value)
    return value


def _grouped_matmul_v5_a4w4_scale(scale_tensor, weight_matmul):
    """Broadcast A4W4 scaleOptional onto the dequantised weight layout.

    perchannel [E,N] -> [E,1,N]; pergroup [E,G,N] -> [E,K,N] with the
    K axis repeated per group. weight_matmul must already be in its
    logical (E,K,N) matmul layout.
    """
    if scale_tensor is None:
        return None
    if not isinstance(scale_tensor, torch.Tensor):
        raise TypeError("GroupedMatmulV5 scaleOptional must be a tensor")
    value = scale_tensor.float()
    k_total = weight_matmul.shape[-2]
    if value.dim() == 2:                       # perchannel [E,N]
        return value.unsqueeze(-2)
    if value.dim() == 3:                       # pergroup [E,G,N]
        groups = value.shape[1]
        if groups <= 0 or k_total % groups != 0:
            raise ValueError(
                "GroupedMatmulV5 A4W4 pergroup scale requires K divisible "
                f"by G (K={k_total}, G={groups})"
            )
        per_group = k_total // groups
        # [E,G,N] -> [E,K,N]（rank-3，与 weight 逐元素对齐）；保留 rank-4
        # [E,K,1,N] 会与 rank-3 weight 右对齐广播错位（E 维撞 K 维）。
        return value.unsqueeze(2).repeat_interleave(per_group, dim=1).squeeze(2)
    raise ValueError(
        "GroupedMatmulV5 A4W4 scaleOptional must be rank-2 [E,N] or rank-3 "
        f"[E,G,N], got rank {value.dim()}"
    )


# ============================================================================
# NPU-side ACLNN function class
# ============================================================================

@register("aclnn_function")
class AclnnGroupedMatmulV5(AclnnBaseApi):
    def init_by_input_data(self, input_data: InputDataset):
        input_tmp={}
        input_args = []
        output_packages = []

        param_list = self.get_param_names_excluding_last_two(self.get_cpp_func_signature_type())
        param_type = self.parse_operator_params(self.get_cpp_func_signature_type())

        self.handle_special_param(self.get_cpp_func_signature_type(), input_data)

        self.handle_attr_param(input_tmp, param_list)

        # ATK 的 convert_input_data 列表分支按位置递归、丢失 dtype="int4"，
        # 张量列表元素永远走通用 create_acl_tensor（INT32 路径）。因此
        # int4 输入必须在此自行展平、逐张量打包为 ACL_INT4 再组回
        # TensorList（逻辑 shape 原样保留）。
        input_names = []
        for item in self.task_result.case_config.inputs:
            if isinstance(item, (list, tuple)):
                input_names.append(
                    getattr(item[0], "name", None) if item else None
                )
            else:
                input_names.append(getattr(item, "name", None))

        for i, arg in enumerate(input_data.args):
            arg_name = input_names[i] if i < len(input_names) else None
            if arg_name is not None and self._int4_config_dtype(
                    arg_name) == "int4":
                if (isinstance(arg, (list, tuple)) and arg
                        and all(isinstance(t, torch.Tensor) for t in arg)):
                    items = [
                        self._create_int4_acl_tensor(t, arg_name)
                        for t in arg
                    ]
                    input_args.append(nnopbase.create_x_list(items))
                    continue
                if isinstance(arg, torch.Tensor):
                    input_args.append(
                        self._create_int4_acl_tensor(arg, arg_name)
                    )
                    continue
            data = self.backend.convert_input_data(arg, index=i)
            input_args.extend(data)
        for name, kwarg in input_data.kwargs.items():
            if name in input_tmp:
                continue
            if self._int4_config_dtype(name) == "int4":
                if (isinstance(kwarg, (list, tuple)) and kwarg
                        and all(isinstance(t, torch.Tensor) for t in kwarg)):
                    items = [
                        self._create_int4_acl_tensor(t, name) for t in kwarg
                    ]
                    if name in param_list:
                        input_tmp[name] = nnopbase.create_x_list(items)
                    continue
                if isinstance(kwarg, torch.Tensor):
                    if name in param_list:
                        input_tmp[name] = [
                            self._create_int4_acl_tensor(kwarg, name)
                        ]
                    continue
            data = self.backend.convert_input_data(kwarg, name=name)
            if name in param_list:
                input_tmp[name] = data

        for i, arg_name in enumerate(param_list):
            data = input_tmp.get(arg_name)
            if data is not None:
                if isinstance(data, list):
                    input_args.extend(data)
                else:
                    input_args.append(data)
            else:
                type = param_type.get(arg_name)
                if type == "aclTensor":
                    AclTensorPtr = ctypes.POINTER(AclTensor)
                    null_void_ptr = ctypes.c_void_p(None)
                    null_tensor_ptr = ctypes.cast(null_void_ptr, AclTensorPtr)
                    input_args.append(null_tensor_ptr)
                elif type == "aclTensorList":
                    AclTensorListPtr = ctypes.POINTER(AclTensorList)
                    null_tensorlist_ptr = AclTensorListPtr()
                    input_args.append(null_tensorlist_ptr)
                elif type == "aclIntArray":
                    AclIntArrayPtr = ctypes.POINTER(AclIntArray)
                    null_intarray_ptr = AclIntArrayPtr()
                    input_args.append(null_intarray_ptr)
                elif type == "aclFloatArray":
                    AclFloatArrayPtr = ctypes.POINTER(AclIntArray)
                    null_floatarray_ptr = AclFloatArrayPtr()
                    input_args.append(null_floatarray_ptr)
                elif type == "aclBoolArray":
                    AclBoolArrayPtr = ctypes.POINTER(AclIntArray)
                    null_boolarray_ptr = AclBoolArrayPtr()
                    input_args.append(null_boolarray_ptr)
                elif type in ("char", "const char") or arg_name == "activation":
                    input_args.append(None)
                else:
                    input_args.append(ctypes.c_void_p(None))

        output_list = self.output.split(',')
        for index, output in enumerate(output_list):
            data = input_tmp.get(output)
            if isinstance(data, list):
                output_packages.append(data[0])
            else:
                output_packages.append(data)

        return input_args, output_packages

    def after_call(self, output_packages):
        output = []
        for output_pack in output_packages:
            if isinstance(output_pack, AclTensorStruct):
                output.append(self.acl_tensor_to_torch(output_pack))
            elif isinstance(output_pack, AclTensorlistStruct):
                output.append(self.acl_tensorlist_to_torch(output_pack))
        return output

    def _x_transposed_presentation(self):
        """gt=2 split-K：x 需以非连续转置张量呈现（x_transposed 卡为真）。"""
        found = self.get_config_by_name(
            self.task_result.case_config.inputs, "x_transposed"
        )
        if found is None:
            return False
        value = getattr(found, "range_values", None)
        while isinstance(value, list) and len(value) == 1:
            value = value[0]
        return bool(value)

    def get_storage_shape(self, input_data: InputDataset, index=None, name=None):
        if name == "x" and self._x_transposed_presentation():
            # 转置呈现：storage 必须上报物理 S（≠ 逻辑 view L）。远端 atk
            # create_acl_tensor 在 storage_shape 缺省时取 view shape（探测源码
            # acl_wrapper.py:298-299），storage==view 会被宿主 CheckCaseSplitK
            # 判为非转置呈现——20260911 run 四变体全败的根因即 storage==view。
            found = self.get_config_by_name(self.task_result.case_config.inputs, name)
            if isinstance(found, list) and found:
                found = found[0]
            if (found is not None and not isinstance(found, list)
                    and found.shape is not None):
                return torch.Size(found.shape)
        if name is not None:
            found = self.get_config_by_name(self.task_result.case_config.inputs, name)
            if (found is not None and not isinstance(found, list)
                    and found.shape is not None):
                return torch.Size(found.shape)
        return None

    def get_format(self, input_data: InputDataset, index=None, name=None):
        found = None
        if name is not None:
            found = self.get_config_by_name(self.task_result.case_config.inputs, name)
        if found is not None and not isinstance(found, list):
            format = found.format
            return self.get_acl_format(format)
        return AclFormat.ACL_FORMAT_ND

    def get_cpp_func_signature_type(self):
        return "aclnnStatus aclnnGroupedMatmulV5GetWorkspaceSize( const aclTensorList *x, const aclTensorList *weight, const aclTensorList *biasOptional, const aclTensorList *scaleOptional, const aclTensorList *offsetOptional, const aclTensorList *antiquantScaleOptional, const aclTensorList *antiquantOffsetOptional, const aclTensorList *perTokenScaleOptional, const aclTensor *groupListOptional, const aclTensorList *activationInputOptional, const aclTensorList *activationQuantScaleOptional, const aclTensorList *activationQuantOffsetOptional, int64_t splitItem, int64_t groupType, int64_t groupListType, int64_t actType, aclIntArray *tuningConfigOptional, aclTensorList *out, aclTensorList *activationFeatureOutOptional, aclTensorList *dynQuantScaleOutOptional, uint64_t *workspaceSize, aclOpExecutor **executor)"

    def get_param_names_excluding_last_two(self, func_str):
        match = re.search(r'\(([^)]*)\)', func_str)
        if not match:
            return []

        params_str = match.group(1)
        param_names = []
        for param in params_str.split(','):
            param = param.strip()
            name_match = re.search(r'\*?\s*(\w+)\s*$', param)
            if name_match:
                param_names.append(name_match.group(1))

        if "GetWorkspaceSize" in func_str:
            return param_names[:-2] if len(param_names) >= 2 else param_names
        else:
            return param_names


    def handle_attr_param(self, input_tmp, param_list):
        for config in self.task_result.case_config.inputs:
            if not isinstance(config, list):
                if config.name not in param_list:
                    continue
                if config.type == "attr":
                    range_val = config.range_values[0] if isinstance(config.range_values, list) else config.range_values
                    ctype = self.get_ctype(config.dtype)
                    if ctype == ctypes.c_char_p:
                        range_val = range_val.encode('utf-8')
                    input_tmp[config.name] = [ctype(range_val)]
            else:
                data = []
                data_name = config[0].name
                if data_name not in param_list:
                    continue
                for config_item in config:
                      if config_item.type == "attrs" or config_item.type == "attr_tuple":
                          range_val = config_item.range_values
                          if isinstance(range_val, list):
                              range_val = range_val[0] if range_val else None
                          if range_val is None:
                              AclIntArrayPtr = ctypes.POINTER(AclIntArray)
                              null_void_ptr = ctypes.c_void_p(None)
                              null_array_ptr = ctypes.cast(null_void_ptr, AclIntArrayPtr)
                              input_tmp[data_name] = null_array_ptr
                              break
                          data.append(self.get_ctype(config_item.dtype)(range_val))
                          input_tmp[data_name] = nnopbase.create_x_list(data)

    def handle_special_param(self, operator_name, input_data):
        if "aclnnGroupedMatmulV5" in operator_name:
            def case_scalar(name, default=None):
                config = self.get_config_by_name(
                    self.task_result.case_config.inputs, name
                )
                value = getattr(config, "range_values", None)
                while isinstance(value, list) and len(value) == 1:
                    value = value[0]
                return default if value is None or isinstance(value, list) else value

            group_type = case_scalar("groupType")
            found_weight_transposed = self.get_config_by_name(
                self.task_result.case_config.inputs, "weight_transposed"
            )
            weight_transposed = False
            if found_weight_transposed is not None:
                value = getattr(found_weight_transposed, "range_values", None)
                if isinstance(value, list):
                    value = value[0] if value else False
                if value is not None:
                    weight_transposed = bool(value)

            flat_configs = []
            for item in self.task_result.case_config.inputs:
                if isinstance(item, (list, tuple)):
                    flat_configs.extend(item)
                else:
                    flat_configs.append(item)

            def config_indexes(name):
                return [
                    index for index, config in enumerate(flat_configs)
                    if (config is not None and hasattr(config, "name")
                        and config.name == name)
                ]

            def runtime_value(name):
                if input_data.kwargs and name in input_data.kwargs:
                    return input_data.kwargs[name]
                indexes = config_indexes(name)
                values = [
                    input_data.args[index] for index in indexes
                    if index < len(input_data.args)
                ]
                if len(values) == 1:
                    return values[0]
                return values or None

            def replace_runtime_value(name, value):
                if input_data.kwargs and name in input_data.kwargs:
                    input_data.kwargs[name] = value
                    return True
                indexes = config_indexes(name)
                if len(indexes) == 1 and indexes[0] < len(input_data.args):
                    input_data.args[indexes[0]] = value
                    return True
                return False

            # A8W4 伪量化多 Tensor 折叠为单 3-D 张量（源码验证，
            # operators-src/gmm/grouped_matmul）：
            # - 宿主/tiling/内核全部按 TensorList[0] 的单张量布局线性寻址：
            #   tiling 取 groupNum=weight[0].dim(0)、quantGroupNum=scale[0].dim(1)、
            #   n=scale[0].dim(2)（grouped_matmul_tiling.cpp:1851-1855）；内核按
            #   groupIdx*n*k 线性偏移读 weight（antiquant_a8w4.h:236-258）。
            # - 多 Tensor 2-D weight（E 个独立 (K,N)）传入时 tiling 把
            #   weight[0].dim(0)=K 当 groupNum、scale[0].dim(1) 当 quantGroupNum、
            #   读越界 dim 当 n → 多重 GM 越界 → MTE invalid GM address
            #   （EZ9999 aicore exception）级联崩溃。A2 宿主检查全为 OP_LOGW
            #   警告不拦截（CheckA8W4SymmQuantParams），须在 executor 侧物化。
            # - 文档合法形态：weight (E,K,N)、scale (E,quantGroupNum,N)（offset
            #   为空）/ (E,1,N)（offset 不为空）、bias (E,N)、offset (E,1,N)。
            #   把 E 个等形 rank-2/rank-1 张量按 dim0 stack 即得。CPU golden
            #   侧收到的是未折叠原始数据（A4W4 x-wrap 同理），multi-weight
            #   路径不受影响；仅当形状不齐/不匹配时跳过折叠，交 NPU 参数
            #   检查产生明确失败供诊断。
            if (group_type == 0
                    and self._int4_config_dtype("x") == "int8"
                    and self._int4_config_dtype("weight") == "int4"):
                def fold_tensor_list(name, item_rank):
                    value = runtime_value(name)
                    if not (isinstance(value, (list, tuple)) and value
                            and all(isinstance(t, torch.Tensor)
                                    for t in value)):
                        return
                    if not all(t.dim() == item_rank for t in value):
                        return
                    if len({tuple(t.shape) for t in value}) != 1:
                        return
                    # ATK 签名校验（check_signature_type_diff）要求
                    # weight/scale/bias/offset 位置传 LP_AclTensorList，
                    # 单张量会被拒（位置 2-5 类型不匹配）；故折叠产物包成
                    # 单元素 TensorList——签名过 list 检查，宿主 tiling 读
                    # weight[0].dim(0)=E（groupNum）也是正确的单张量视图。
                    replace_runtime_value(
                        name, [torch.stack(list(value), dim=0)]
                    )

                fold_tensor_list("scaleOptional", 2)   # E×(G,N) -> [(E,G,N)]
                fold_tensor_list("biasOptional", 1)    # E×(N,)  -> [(E,N)]
                fold_tensor_list("offsetOptional", 2)  # E×(1,N) -> [(E,1,N)]
                fold_tensor_list("weight", 2)          # E×(K,N) -> [(E,K,N)]

            def prepare_weight_tensor(tensor):
                return _prepare_grouped_matmul_v5_weight(
                    tensor, group_type, weight_transposed
                )

            def prepare_weight_value(value):
                if isinstance(value, torch.Tensor):
                    return prepare_weight_tensor(value)
                if isinstance(value, list):
                    return [prepare_weight_tensor(item) for item in value]
                if isinstance(value, tuple):
                    return tuple(prepare_weight_tensor(item) for item in value)
                return value

            handled_in_kwargs = bool(
                input_data.kwargs and "weight" in input_data.kwargs
            )
            if handled_in_kwargs:
                input_data.kwargs["weight"] = prepare_weight_value(
                    input_data.kwargs["weight"]
                )
            elif input_data.args:
                weight_indexes = [
                    index for index, config in enumerate(flat_configs)
                    if (config is not None and hasattr(config, "name")
                        and config.name == "weight")
                ]
                for index in weight_indexes:
                    if index < len(input_data.args):
                        input_data.args[index] = prepare_weight_value(
                            input_data.args[index]
                        )

            # gt=2 split-K x 转置呈现（文档场景表：gt=2 x 必须转置；宿主
            # CheckCaseSplitK 校验）。cases 层 x 存物理 S + is_transpose/
            # transpose_id（permute(S, perm) == 逻辑 view L）；此处把 x 还原为
            # L 的非连续 view（strides 经 convert_input_data → create_acl_tensor
            # 传导给 ACL 描述符），storage 侧由 get_storage_shape 对转置 x
            # 上报物理 S（storage≠view 才构成宿主认可的转置呈现）。
            if self._x_transposed_presentation():
                def permute_x_tensor(tensor):
                    if not isinstance(tensor, torch.Tensor) or tensor.dim() < 2:
                        return tensor
                    found_x = self.get_config_by_name(
                        self.task_result.case_config.inputs, "x"
                    )
                    if isinstance(found_x, list) and found_x:
                        found_x = found_x[0]
                    perm = getattr(found_x, "transpose_id", None) \
                        if found_x is not None else None
                    if isinstance(perm, (list, tuple)) \
                            and len(perm) == tensor.dim():
                        return tensor.permute(*[int(p) for p in perm])
                    # 配置未透传 transpose_id 时的等价回退：末两维转置
                    # （gt=2 x 为 rank-2 (K,M) 存储，等价 perm [1,0]）。
                    return tensor.transpose(-1, -2)

                x_runtime = runtime_value("x")
                x_items = (
                    list(x_runtime) if isinstance(x_runtime, (list, tuple))
                    else [x_runtime]
                )
                if x_items and all(
                        isinstance(t, torch.Tensor) for t in x_items):
                    permuted = [permute_x_tensor(t) for t in x_items]
                    replace_runtime_value(
                        "x",
                        permuted if isinstance(x_runtime, (list, tuple))
                        else permuted[0],
                    )

            # A4W4 x 物化：ATK 以 torch.int32 逻辑值生成 int4 数据，先折算
            # 到 [-8,7] 的 int8，init_by_input_data 再打包为 ACL_INT4。
            # 须在 groupList 物化前完成，使作用域检查按 int8 命中。
            if self._int4_config_dtype("x") == "int4":
                x_runtime = runtime_value("x")
                if x_runtime is not None:
                    replace_runtime_value(
                        "x", _int4_nibble_wrap_value(x_runtime)
                    )

            # A4W4 内核缺陷补偿：文档声明 perTokenScaleOptional 可选，宿主
            # CheckA4W4 对 null 合法放行且直接把 nullptr 透传给内核
            # （IsEmpty() ? nullptr），但 GMMA4W4Compute 内核无条件执行
            # perTokenScaleGm SetGlobalBuffer + DataCopyPad 读取，null 时
            # 即 "MTE accesses an invalid GM address" 崩溃。此处当 A4W4 且
            # 用例未提供 perTokenScale 时物化全 1 的 fp32 [M] 张量（乘 1
            # 恒等，数值语义不变；宿主要求 1 维且长度=x 的 M）。
            if (self._int4_config_dtype("x") == "int4"
                    and self._int4_config_dtype("weight") == "int4"
                    and input_data.kwargs is not None
                    and "perTokenScaleOptional" not in input_data.kwargs):
                x_probe = runtime_value("x")
                if isinstance(x_probe, (list, tuple)):
                    x_probe = x_probe[0] if len(x_probe) == 1 else None
                if isinstance(x_probe, torch.Tensor) and x_probe.dim() >= 2:
                    input_data.kwargs["perTokenScaleOptional"] = [
                        torch.ones(
                            int(x_probe.shape[0]), dtype=torch.float32
                        )
                    ]

            # A8W4 内核缺陷补偿（源码验证）：与 A4W4 同族——MSD/ND 模板
            # DataCopyPerTokenScaleAndBrcb 无条件 perTokenScaleGm
            # SetGlobalBuffer + DataCopyPad 读取（antiquant_a8w4.h:346、
            # msd.h:450，无 null 守卫），宿主 perTokenScale 为空时把
            # nullptr 透传给内核（aclnn_grouped_matmul.cpp:2318）→ MTE
            # invalid GM address 崩溃。且非对称分支（offsetOptional (E,1,N)
            # 非空）宿主硬检查要求 perTokenScale 非空、fp32 且 shape
            # (M,1) rank-2（CheckA8W4AsymQuantParams /
            # CheckA8W4AsymQuantParamsRelationship，aclnn:963-1023）；对称
            # 分支仅 LOGW（dim[0]==M 即可通过）。此处当 A8W4 且用例未提供
            # perTokenScale 时物化全 1 的 fp32 (M,1) 张量（乘 1 恒等，数值
            # 语义不变）；用户显式提供的 perTokenScale 原样透传（如 rank-1
            # (M,) 会按宿主硬检查明确拒绝，留给约束诊断）。
            if (group_type == 0
                    and self._int4_config_dtype("x") == "int8"
                    and self._int4_config_dtype("weight") == "int4"
                    and input_data.kwargs is not None
                    and "perTokenScaleOptional" not in input_data.kwargs):
                x_probe = runtime_value("x")
                if isinstance(x_probe, (list, tuple)):
                    x_probe = x_probe[0] if len(x_probe) == 1 else None
                if isinstance(x_probe, torch.Tensor) and x_probe.dim() == 2:
                    input_data.kwargs["perTokenScaleOptional"] = [
                        torch.ones(
                            (int(x_probe.shape[0]), 1), dtype=torch.float32
                        )
                    ]

            # groupListType 0/1/2 materialisation
            group_list_type = case_scalar("groupListType")
            group_list_tensor = runtime_value("groupListOptional")
            group_list = _prepare_grouped_matmul_v5_group_list(
                runtime_value("x"), runtime_value("weight"), group_list_tensor,
                group_type, group_list_type
            )
            if group_list is not group_list_tensor:
                replace_runtime_value("groupListOptional", group_list)

            if input_data.kwargs:
                input_data.kwargs.pop("activationFeatureOutOptional", None)
                input_data.kwargs.pop("dynQuantScaleOutOptional", None)
            return


    def parse_operator_params(self, func_signature: str):
        params_match = re.search(r'\((.*?)\)\s*$', func_signature, re.DOTALL)
        if not params_match:
            return {}

        params_str = params_match.group(1)
        params = []
        current_param = ""
        angle_bracket_count = 0
        paren_count = 0

        for char in params_str:
            if char == '<':
                angle_bracket_count += 1
            elif char == '>':
                angle_bracket_count -= 1
            elif char == '(':
                paren_count += 1
            elif char == ')':
                paren_count -= 1
            elif char == ',' and angle_bracket_count == 0 and paren_count == 0:
                params.append(current_param.strip())
                current_param = ""
                continue
            current_param += char

        if current_param.strip():
            params.append(current_param.strip())

        result = {}
        for param in params:
            match = re.match(r'^(const\s+)?(.+?)\s+(\*?\s*)([a-zA-Z_][a-zA-Z0-9_]*)(\s*=\s*.*)?$', param.strip())
            if match:
                param_type = match.group(2).strip()
                param_name = match.group(4).strip()
                param_type = param_type.replace('const ', '').replace('const', '').strip()
                param_type = param_type.replace('*', '').strip()
                result[param_name] = param_type
        return result

    def get_config_by_name(self, configs, target_name: str):
        for item in configs:
            if isinstance(item, list):
                if item and hasattr(item[0], 'name') and item[0].name == target_name:
                    return item
            elif hasattr(item, 'name') and item.name == target_name:
                return item
        return None

    def _unwrap_config(self, name):
        found = self.get_config_by_name(
            self.task_result.case_config.inputs, name
        )
        if isinstance(found, (list, tuple)):
            found = found[0] if found else None
        return found

    def _int4_config_dtype(self, name):
        found = self._unwrap_config(name)
        return getattr(found, "dtype", None) if found is not None else None

    def _create_int4_acl_tensor(self, tensor, name):
        """Pack an int8 tensor (values in [-8, 7]) into an ACL_INT4 tensor.

        存储格式沿用 cases 配置的 format（ND/NZ）；storage_shape 缺省取
        tensor.shape（逻辑 shape），ACL_INT4 按 2 nibble/byte 计算物理
        存储大小，无需压缩末维。

        weight_transposed 物化（末两维转置视图）：ACL 视图 shape 恒为
        (E,K,N)（dim1=K 与 x 对齐），转置语义由 strides 表达（宿主
        IsTransposeLastTwoDims 判定 transposeWeight）；nibble 打包按物理
        存储顺序（视图再转置回 contiguous 的数据），shape/strides 按视图
        报告。ATK 自带的 create_int4_acl_tensor 会 contiguous() 重排数据
        破坏该对应关系，转置视图必须走本地打包路径。
        """
        found = self._unwrap_config(name)
        fmt = AclFormat.ACL_FORMAT_ND
        config_format = getattr(found, "format", None) if found else None
        if config_format:
            fmt = self.get_acl_format(config_format)
        view = tensor
        pack_src = tensor
        if (isinstance(view, torch.Tensor) and view.dim() >= 2
                and not view.is_contiguous()):
            pack_src = view.transpose(-1, -2).contiguous()
        return self._pack_int4_acl_tensor(view, pack_src, fmt)

    def _pack_int4_acl_tensor(self, view, pack_src, fmt):
        """Pack pack_src data as ACL_INT4, reporting view's shape/strides."""
        if pack_src.device.type != 'npu':
            pack_src = pack_src.npu().clone()
        if pack_src.dtype != torch.int8:
            raise TypeError(
                f"int4 input data must be torch.int8, but got {pack_src.dtype}"
            )
        if not torch.all((pack_src >= -8) & (pack_src <= 7)):
            num_bad = torch.sum((pack_src < -8) | (pack_src > 7)).item()
            raise ValueError(
                f"int4 input data contains {num_bad} values out of int4 "
                "range [-8, 7]"
            )

        dtype = AclDataType.ACL_INT4
        t_flat = pack_src.contiguous().view(-1).clone().npu()
        t_flat[t_flat < 0] += 16  # 补码表示
        if t_flat.numel() % 2 != 0:
            t_flat = torch.cat(
                [t_flat, torch.zeros(1, dtype=torch.int8).npu()], dim=0
            )
        low = t_flat[0::2]
        high = t_flat[1::2]
        packed = (high << 4) | low
        packed = packed.to(torch.uint8)
        nnopbase.int4_cache.append(packed)

        device_addr = ctypes.c_void_p(packed.data_ptr())
        view_shape = tuple(int(v) for v in view.shape)
        view_strides = tuple(int(s) for s in view.stride())
        storage_shape = view_shape
        acl_tensor = nnopbase.aclCreateTensor(
            (Int64 * len(view_shape))(*view_shape), len(view_shape),
            dtype, (Int64 * len(view_strides))(*view_strides), 0, fmt,
            (Int64 * len(storage_shape))(*storage_shape),
            len(storage_shape), device_addr
        )
        if not acl_tensor:
            raise RuntimeError("aclCreateTensor returned nullptr")
        return AclTensorStruct(acl_tensor, device_addr.value, view, 1)

    def get_acl_format(self, format_str):
        FORMAT_MAPPING = {
            'ND': AclFormat.ACL_FORMAT_ND,
            'NZ': AclFormat.ACL_FORMAT_FRACTAL_NZ,
            'NCHW': AclFormat.ACL_FORMAT_NCHW,
            'NC': AclFormat.ACL_FORMAT_NC,
            'HWCN': AclFormat.ACL_FORMAT_HWCN,
            'NHWC': AclFormat.ACL_FORMAT_NHWC,
            'NC1HWC0': AclFormat.ACL_FORMAT_NC1HWC0,
            'NDC1HWC0': AclFormat.ACL_FORMAT_NDC1HWC0,
            'NCL': AclFormat.ACL_FORMAT_NCL,
            'NCDHW': AclFormat.ACL_FORMAT_NCDHW,
            'NDHWC': AclFormat.ACL_FORMAT_NDHWC,
            'FRACTAL_Z_3D': AclFormat.ACL_FRACTAL_Z_3D,
        }
        if format_str in FORMAT_MAPPING:
            return FORMAT_MAPPING[format_str]
        else:
            logging.error(f"not found format: {format_str}")
            return AclFormat.ACL_FORMAT_ND

    def get_ctype(self, type_str):
        PYTYPE_TO_CTYPE = {
            "float": ctypes.c_float,
            "float32": ctypes.c_float,
            "float64": ctypes.c_double,
            "fp": ctypes.c_float,
            "fp32": ctypes.c_float,
            "fp64": ctypes.c_double,
            "double": ctypes.c_double,
            "int": ctypes.c_int64,
            "int8_t": ctypes.c_int8,
            "int8": ctypes.c_int8,
            "int32_t": ctypes.c_int32,
            "int32": ctypes.c_int32,
            "int64_t": ctypes.c_int64,
            "int64": ctypes.c_int64,
            "uint8_t": ctypes.c_uint8,
            "uint8": ctypes.c_uint8,
            "uint32_t": ctypes.c_uint32,
            "uint32": ctypes.c_uint32,
            "uint64_t": ctypes.c_uint64,
            "uint64": ctypes.c_uint64,
            "bool": ctypes.c_bool,
            "attr_bool": ctypes.c_bool,
            "str": ctypes.c_char_p,
            "string": ctypes.c_char_p,
        }
        if type_str in PYTYPE_TO_CTYPE:
            return PYTYPE_TO_CTYPE[type_str]
        else:
            raise ValueError(f"Unsupported CTYPE format: {type_str}")


# ============================================================================
# CPU-side golden reference class
# ============================================================================

@register("function")
class Function(BaseApi):
    """CPU reference class for aclnnGroupedMatmulV5 — fixed golden template."""

    _OP_NAME = "aclnnGroupedMatmulV5"
    _SIG_STR = """aclnnStatus aclnnGroupedMatmulV5GetWorkspaceSize( const aclTensorList *x, const aclTensorList *weight, const aclTensorList *biasOptional, const aclTensorList *scaleOptional, const aclTensorList *offsetOptional, const aclTensorList *antiquantScaleOptional, const aclTensorList *antiquantOffsetOptional, const aclTensorList *perTokenScaleOptional, const aclTensor *groupListOptional, const aclTensorList *activationInputOptional, const aclTensorList *activationQuantScaleOptional, const aclTensorList *activationQuantOffsetOptional, int64_t splitItem, int64_t groupType, int64_t groupListType, int64_t actType, aclIntArray *tuningConfigOptional, aclTensorList *out, aclTensorList *activationFeatureOutOptional, aclTensorList *dynQuantScaleOutOptional, uint64_t *workspaceSize, aclOpExecutor **executor)"""
    _INPUT_PARAM_NAMES = ['x', 'weight', 'biasOptional', 'scaleOptional', 'offsetOptional', 'antiquantScaleOptional', 'antiquantOffsetOptional', 'perTokenScaleOptional', 'groupListOptional', 'activationInputOptional', 'activationQuantScaleOptional', 'activationQuantOffsetOptional', 'splitItem', 'groupType', 'groupListType', 'actType', 'tuningConfigOptional']
    _OUTPUT_PARAM_NAMES = ['out']
    _REQUIRED_TENSOR_NAMES = ['x', 'weight']

    def __call__(self, input_data: InputDataset, with_output: bool = False):
        # ---- Parameter extraction (compatible with both kwargs and args) ----
        _param_map = {}
        _kwargs = getattr(input_data, "kwargs", None) or {}
        for _name, _value in _kwargs.items():
            _param_map[_name] = _value
            if isinstance(_name, str):
                _param_map[_name.lower()] = _value

        _args = getattr(input_data, "args", None) or []
        _flat_configs = []
        _task_result = getattr(self, "task_result", None)
        _case_config = getattr(_task_result, "case_config", None)
        for _item in (getattr(_case_config, "inputs", None) or []):
            if isinstance(_item, (list, tuple)):
                _flat_configs.extend(_item)
            else:
                _flat_configs.append(_item)

        _case_attr_map = {}
        for _config in _flat_configs:
            _config_type = getattr(_config, "type", None)
            if _config_type not in ("attr", "attrs", "attr_tuple"):
                continue
            _name = getattr(_config, "name", None)
            if not _name:
                continue
            _value = getattr(_config, "range_values", None)
            while isinstance(_value, (list, tuple)) and len(_value) == 1:
                _value = _value[0]
            if isinstance(_value, (list, tuple)):
                continue
            if _value is not None:
                _case_attr_map[_name] = _value
                if isinstance(_name, str):
                    _case_attr_map[_name.lower()] = _value
        for _index, _value in enumerate(_args):
            _name = None
            if _index < len(_flat_configs):
                _name = getattr(_flat_configs[_index], "name", None)
            if not _name and _index < len(self._INPUT_PARAM_NAMES):
                _name = self._INPUT_PARAM_NAMES[_index]
            if _name and _name not in _param_map:
                _param_map[_name] = _value
                _param_map[_name.lower()] = _value

        def _get_param(name, default=None):
            value = _param_map.get(name)
            if value is None and isinstance(name, str):
                value = _param_map.get(name.lower())
            if value is None:
                value = _case_attr_map.get(name)
            if value is None and isinstance(name, str):
                value = _case_attr_map.get(name.lower())
            return default if value is None else value

        def _get_tensor(name, default=None):
            value = _get_param(name, default)
            if isinstance(value, torch.Tensor):
                return value
            if isinstance(value, (list, tuple)) and all(
                    isinstance(item, torch.Tensor) for item in value):
                return value
            if value is not None and hasattr(value, "__array__"):
                try:
                    return torch.as_tensor(value)
                except (TypeError, ValueError, RuntimeError):
                    pass
            return default

        _missing_required = [
            name for name in self._REQUIRED_TENSOR_NAMES
            if _get_tensor(name) is None
        ]
        if _missing_required:
            _available = {
                str(name): type(value).__name__
                for name, value in _param_map.items()
                if not isinstance(name, str) or name == name.lower()
            }
            raise TypeError(
                f"{self._OP_NAME} CPU golden missing required tensor inputs "
                f"{_missing_required}; available={_available}; "
                f"args_types={[type(value).__name__ for value in _args]}; "
                f"kwargs_keys={list(_kwargs.keys())}"
            )

        # ---- CPU golden: MOCKED (2026-09-21, 与通用模板生成时 mock 同构) ----
        # 按 out 占位张量返回同 shape/dtype 的全零张量，ATK 用其物化 NPU 输出、
        # kernel 真实执行；精度比对无业务语义（对比的是 mock zeros）。输入/输出
        # 为 TensorList，展开时保留列表结构；保留输出 activationFeatureOutOptional
        # / dynQuantScaleOutOptional 由 NPU 侧以 nullptr 表示，不参与 mock。
        # 原 groupType=-1/0/2 反量化与分组 matmul 推导已移除，恢复参考 git 历史。
        def _zeros_like_value(value):
            if isinstance(value, torch.Tensor):
                return torch.zeros_like(value)
            if isinstance(value, (list, tuple)):
                items = [_zeros_like_value(item) for item in value]
                if items and all(item is not None for item in items):
                    return items
                return None
            return None

        _mock_outputs = []
        for _name in self._OUTPUT_PARAM_NAMES:
            _mock_outputs.append(_zeros_like_value(_get_tensor(_name)))
        if _mock_outputs and all(item is not None for item in _mock_outputs):
            if len(_mock_outputs) == 1:
                return _mock_outputs[0]
            return _mock_outputs
        # Fallback chain: first required input tensor, then fixed dummy.
        for _name in self._REQUIRED_TENSOR_NAMES:
            _candidate = _zeros_like_value(_get_tensor(_name))
            if _candidate is not None:
                return _candidate
        return torch.zeros(1, dtype=torch.float16)

