#!/usr/bin/env python3
"""Generate .claude/skills wrappers for every manifest knowledge module.

canonical 保持在 ``knowledge/<family>/**``（唯一编辑源，prompt 演进流程不变）；
本脚本把每个 manifest 模块渲染成 ``.claude/skills/<prefix><id>/SKILL.md``
生成物，供任意阶段、任意 Agent 通过 Skill 工具按需加载。

- 生成物禁止手改；validator（validate_*_knowledge.py）逐字节比对生成物与
  canonical 渲染结果，漂移即 fail（init_run 预校验自动拦截）。
- description 由模块 frontmatter ``description`` + 触发器关键词 + 阶段信号
  合成为单行——这一行决定自然触发质量，改动需同步本脚本模板。
- 清理：前缀匹配但不在当前 manifest 中的 skill 目录会被删除，防止模块
  退场后残留误导触发。
"""
from __future__ import annotations

import argparse
import hashlib
import json
import shutil
from pathlib import Path

try:
    from scripts.route_aclnn_knowledge import _load_modules as _load_aclnn
    from scripts.route_torch_npu_knowledge import _load_modules as _load_torch
except ModuleNotFoundError:  # pragma: no cover - alternate package path
    from route_aclnn_knowledge import _load_modules as _load_aclnn
    from route_torch_npu_knowledge import _load_modules as _load_torch


ROOT = Path(__file__).resolve().parents[1]
SKILLS_ROOT = ROOT / ".claude" / "skills"
FAMILY_KNOWLEDGE = {
    "aclnn": ROOT / "knowledge" / "aclnn",
    "torch_npu": ROOT / "knowledge" / "torch_npu",
}
FAMILY_SKILL_PREFIX = {"aclnn": "aclnn-", "torch_npu": "torch-npu-"}
FAMILY_LABEL = {"aclnn": "ACLNN", "torch_npu": "torch_npu"}
_GENERATED_NOTE = (
    "GENERATED by scripts/build_knowledge_skills.py — 禁止手改。\n"
    "     canonical: {canonical}\n"
    "     sha256(canonical): {digest}\n"
    "     修改流程：编辑 canonical → python scripts/build_knowledge_skills.py\n"
    "     → python scripts/validate_{validator} （同步校验在 init_run 预校验中自动执行）"
)
_VALIDATOR = {"aclnn": "aclnn_knowledge", "torch_npu": "torch_npu_knowledge"}


def _sha_text(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def skill_name(family: str, module_id: str) -> str:
    return FAMILY_SKILL_PREFIX[family] + module_id.replace("_", "-")


def module_description(raw: str) -> str:
    """frontmatter 的 description 单行（route_*_knowledge.parse_frontmatter 未解析该字段）。"""
    lines = raw.splitlines()
    for index, line in enumerate(lines):
        stripped = line.strip()
        if index > 0 and stripped == "---":
            break
        if stripped.startswith("description:"):
            return stripped.split(":", 1)[1].strip().strip("\"'")
    return ""


def _trigger_summary(trigger: dict) -> str:
    kind, value = trigger.get("kind"), trigger.get("value")
    if isinstance(value, list):
        value = "|".join(str(x) for x in value)
    value = str(value).replace("(?i)", "").strip()
    labels = {
        "operator_name_eq": "算子=",
        "operator_name_regex": "算子名匹配",
        "name_contains": "算子名含",
        "doc_contains": "",
        "format_any": "format含",
        "file_name_regex": "文件名匹配",
    }
    label = labels.get(kind, f"{kind}:")
    return f"{label}{value}" if label else value


def synthesize_description(family: str, item: dict) -> str:
    desc = module_description(item["raw"]) or item.get("module", item.get("id", ""))
    parts = [f"{FAMILY_LABEL[family]}·{item.get('scope', 'knowledge')}知识", desc]
    signals = [_trigger_summary(t) for t in item.get("triggers", [])]
    if signals:
        parts.append("信号：" + "；".join(signals))
    deps = [skill_name(family, d) for d in item.get("depends_on", [])]
    if deps:
        parts.append("依赖：先加载 " + "、".join(deps))
    return "。".join(parts) + "。涉及这些信号时加载；诊断相关失败、修改或校验相关约束时也加载。"


def _yaml_single_quoted(text: str) -> str:
    """YAML 单引号标量：仅单引号需双写，其余字符（含反斜杠、|）字面保留。"""
    return "'" + text.replace("'", "''") + "'"


def render_skill(family: str, item: dict) -> str:
    name = skill_name(family, item["module"])
    canonical = FAMILY_KNOWLEDGE[family] / item.get("path", "")
    note = _GENERATED_NOTE.format(
        canonical=canonical.relative_to(ROOT).as_posix(),
        digest=_sha_text(item["raw"]),
        validator=_VALIDATOR[family],
    )
    # frontmatter 必须位于文件首行（Claude Code 按首部 YAML 解析 name/description）；
    # GENERATED 注释放 frontmatter 之后。
    lines = [
        "---",
        f"name: {name}",
        f"description: {_yaml_single_quoted(synthesize_description(family, item))}",
        "---",
        "",
        f"<!-- {note} -->",
        "",
        item["body"].rstrip(),
        "",
    ]
    deps = [skill_name(family, d) for d in item.get("depends_on", [])]
    if deps:
        lines.extend([
            "---",
            "<!-- 依赖模块：如本 skill 被单独触发，先 Skill 加载 "
            + "、".join(deps)
            + " -->",
            "",
        ])
    return "\n".join(lines)


def _family_modules(family: str, knowledge: Path | None = None) -> dict:
    root = knowledge or FAMILY_KNOWLEDGE[family]
    loader = _load_aclnn if family == "aclnn" else _load_torch
    _, modules = loader(root)
    return modules


def build_family(family: str, knowledge: Path | None = None) -> list[str]:
    modules = _family_modules(family, knowledge)
    prefix = FAMILY_SKILL_PREFIX[family]
    expected = {skill_name(family, mid) for mid in modules}
    generated: list[str] = []
    if SKILLS_ROOT.is_dir():
        for stale in SKILLS_ROOT.iterdir():
            if stale.is_dir() and stale.name.startswith(prefix) and stale.name not in expected:
                shutil.rmtree(stale)
    for module_id, item in modules.items():
        name = skill_name(family, module_id)
        target = SKILLS_ROOT / name / "SKILL.md"
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(render_skill(family, item), encoding="utf-8")
        generated.append(name)
    return sorted(generated)


def check_family(family: str, knowledge: Path | None = None) -> list[str]:
    """同步校验：skill 集合与 manifest 一一对应且内容与渲染结果逐字节一致。"""
    errors: list[str] = []
    modules = _family_modules(family, knowledge)
    prefix = FAMILY_SKILL_PREFIX[family]
    expected = {skill_name(family, mid) for mid in modules}
    actual: set[str] = set()
    if SKILLS_ROOT.is_dir():
        actual = {
            p.name for p in SKILLS_ROOT.iterdir()
            if p.is_dir() and p.name.startswith(prefix)
        }
    for extra in sorted(actual - expected):
        errors.append(f"stale generated skill without manifest module: {extra}")
    for module_id in sorted(expected - actual):
        errors.append(
            f"manifest module has no generated skill: {module_id} -> {skill_name(family, module_id)}"
        )
    for module_id, item in modules.items():
        name = skill_name(family, module_id)
        path = SKILLS_ROOT / name / "SKILL.md"
        if not path.is_file():
            errors.append(f"missing skill file: {path}")
            continue
        if path.read_text(encoding="utf-8") != render_skill(family, item):
            errors.append(
                f"skill out of sync with canonical (rerun build_knowledge_skills.py): {path}"
            )
    return errors


def render_required_list(family: str, entries: list[dict]) -> str:
    """渲染 prompt_v1.md 的必载知识清单（entries 由 select_*_prompt 从路由结果构造）。"""
    lines = [
        "<!-- required-knowledge-begin -->", "",
        "## 本次必载知识清单（确定性路由命中）", "",
        "以下模块已由 run 初始化阶段的知识路由确认命中。提取时必须**逐一用 Skill 工具"
        "加载并应用**；认为某模块对本算子不适用的，必须在"
        " `extraction_provenance.json` 中记录 `not_applicable` 及理由，不得静默跳过。"
        "除清单外，文档出现其他信号时也应自主加载对应的"
        f" `{FAMILY_SKILL_PREFIX[family]}*` skill。", "",
        "| # | Skill | 作用 | 命中依据 |",
        "|---|---|---|---|",
    ]
    for order, entry in enumerate(entries, 1):
        evidence = "；".join(entry.get("evidence", []))
        if len(evidence) > 120:
            evidence = evidence[:117] + "..."
        desc = entry.get("description", "").replace("|", "\\|")
        evidence = evidence.replace("|", "\\|").replace("\n", " ")
        lines.append(
            f"| {order} | {skill_name(family, entry['module_id'])} | {desc} | {evidence} |"
        )
    lines.extend(["", "<!-- required-knowledge-end -->", ""])
    return "\n".join(lines)


def required_list_entries(result: dict, knowledge: Path | None = None, family: str = "aclnn") -> list[dict]:
    """把 route() 结果 + 模块 frontmatter 组装成 render_required_list 的输入。"""
    modules = _family_modules(family, knowledge)
    decisions = {d["module_id"]: d for d in result["applicability"]["selected_modules"]}
    entries = []
    for module_id in result["resolved_modules"]:
        item = modules[module_id]
        entries.append({
            "module_id": module_id,
            "scope": item.get("scope", ""),
            "description": module_description(item["raw"]),
            "evidence": decisions.get(module_id, {}).get("evidence", []),
        })
    return entries


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate .claude/skills wrappers from knowledge manifests."
    )
    parser.add_argument("--family", choices=["aclnn", "torch_npu", "all"], default="all")
    parser.add_argument(
        "--check", action="store_true",
        help="只校验同步状态不写文件；不同步时 exit 2。",
    )
    args = parser.parse_args()
    families = ["aclnn", "torch_npu"] if args.family == "all" else [args.family]
    if args.check:
        errors: dict[str, list[str]] = {}
        for family in families:
            errors[family] = check_family(family)
        ok = not any(errors.values())
        print(json.dumps({"ok": ok, "errors": errors}, ensure_ascii=False, indent=2))
        return 0 if ok else 2
    generated: dict[str, list[str]] = {}
    for family in families:
        generated[family] = build_family(family)
    print(json.dumps({"ok": True, "generated": generated}, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
