#!/usr/bin/env python3
"""Print project Skills, Agents, their preload relations, and dispatch flow."""

from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def frontmatter(path: Path) -> dict[str, object]:
    text = path.read_text(encoding="utf-8")
    match = re.match(r"^---\s*\n(.*?)\n---", text, re.S)
    if not match:
        return {}
    data: dict[str, object] = {}
    current_list: str | None = None
    for raw in match.group(1).splitlines():
        if raw.startswith("  - ") and current_list:
            value = str(data.get(current_list, ""))
            item = raw[4:].strip()
            data[current_list] = f"{value}, {item}".strip(", ")
            continue
        current_list = None
        if ":" not in raw:
            continue
        key, value = raw.split(":", 1)
        key, value = key.strip(), value.strip()
        if len(value) >= 2 and value[0] == value[-1] and value[0] in "'\"":
            value = value[1:-1].replace("''", "'") if value[0] == "'" else value[1:-1]
        data[key] = value
        if not value:
            current_list = key
    return data


def clipped(value: object, width: int = 52) -> str:
    text = str(value or "-")
    return text if len(text) <= width else text[: width - 1] + "…"


def main() -> int:
    print("=== Claude Code Workforce ===")
    flow_skills: list[tuple[str, object]] = []
    knowledge_skills: list[tuple[str, object]] = []
    for path in sorted((ROOT / ".claude" / "skills").glob("*/SKILL.md")):
        meta = frontmatter(path)
        head = path.read_text(encoding="utf-8", errors="replace").splitlines()[:8]
        entry = (path.parent.name, meta.get("description"))
        if any("GENERATED by scripts/build_knowledge_skills.py" in line for line in head):
            knowledge_skills.append(entry)
        else:
            flow_skills.append(entry)

    print("\nSkills")
    for name, description in flow_skills:
        print(f"  /{name:<22} {clipped(description)}")

    print(f"\nKnowledge skills（生成物，按需触发加载；共 {len(knowledge_skills)} 个）")
    for name, description in knowledge_skills:
        print(f"  *{name:<28} {clipped(description, 60)}")

    print("\nAgents")
    for path in sorted((ROOT / ".claude" / "agents").glob("*.md")):
        meta = frontmatter(path)
        name = str(meta.get("name") or path.stem)
        skills = str(meta.get("skills") or "-")
        print(f"  @{name:<22} skill={skills:<22} {clipped(meta.get('description'), 44)}")

    print("\nDispatch")
    print("  PLAN -> constraint-extractor -> optional constraint-supplementer")
    print("       -> constraint-checker <-> constraint-repairer -> case-generator -> case-executor")
    print("       -> quality-reviewer -> SUCCESS")
    print("       -> failure-analyst -> UPDATE_CONSTRAINTS -> constraint-updater")
    print("       -> constraint-checker <-> constraint-repairer -> next generation")
    print("       -> mixed failures -> REVIEW | generator_bug/executor_bug -> STOP")
    print(
        "\nLive views: /agents (instances) | /hooks (lifecycle) | "
        "/iterate-operator (run) | /iterate-directory (batch)"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
